name: "Copyright Action"
description: "Inserts copyright notice to configured files in repository and creates a pull request"
author: "anu"
branding:
  icon: "edit"
  color: "gray-dark"
inputs:
  # Required
  CopyrightString:
    description: String to be added as Copyright notice(multiline copyrights are possible)
    requried: true

  FileType:
    description: Type of files(extension) for which copyright notice has to be added in the given file path
    requried: true

  # Optional
  Path:
    description: Path in which copyright notice has to be added to files
    requried: false

  IgnorePath:
    description: Path ignored without adding copyright notice
    requried: false
runs:
  using: "docker"
  image: "Dockerfile"
